---
title: 'Data Viz.: Homework 7'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)
library(readxl)
library(httr)
library(plotly)
library(RColorBrewer)
```

## Continuous variable

### Import & format data
```{r}
GET('http://www.africapolis.org/download/Africapolis_agglomeration_2015.xlsx', 
    write_disk(africapolis_impt <- tempfile(fileext = ".xls")))
```

```{r pressure, echo=FALSE}
afr_cities <- read_xlsx(africapolis_impt, 
               skip = 15, 
               col_types = c("text", "text", "text", rep("numeric", 7), 
                             "text", rep("numeric", 8)), 
               na = c('-', 'M', ''))

afr_cities <- afr_cities %>%
  rename(closest_metro = `Closest Metro`, 
         dist_to_metro = `Distance to metro`)
```

```{r}
# ggplot(afr_cities, aes(x = Population_2015, y = Builtup)) +
#   geom_point()
```

```{r}
hub_cities <- afr_cities %>%
  drop_na(closest_metro) %>%
  group_by(closest_metro) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  head(5)

hub_cities
```
```{r fig.height= 6, fig.width=4}
# test <- afr_cities %>%
#   filter(closest_metro %in% hub_cities$closest_metro) %>%
#   filter(dist_to_metro > 0) %>%
#   filter(Population_2015 < 500000)
# 
# 
# ggplot(test, aes(x = dist_to_metro, y = Population_2015)) +
#   theme_classic() +
#   scale_y_log10(labels = scales::comma) +
#   geom_point(color = "lightblue") +
#   geom_smooth(method = 'lm', formula = y ~ splines::bs(x, 3), se = FALSE, color = "steelblue") +
#   facet_grid(rows = vars(factor(closest_metro)))
# 
# ?geom_smooth
```

```{r fig.height= 6, fig.width=4}
# ggplot(test, aes(x = Population_2015, y = Builtup)) +
#   theme_classic() +
#   scale_y_continuous(labels = scales::comma) +
#   scale_x_continuous(labels = scales::comma) +
#   geom_point() +
#   geom_smooth(method = 'lm', formula = y ~ splines::bs(x, 3), se = FALSE) +
#   facet_grid(rows = vars(factor(closest_metro)))
```



```{r fig.height=8, fig.width=4}
color <- brewer.pal(4, "Set1")

# set up title formatting
title <- list(
  text = "Relationship Between Job Prestige of R and Spouse",
  xref = "paper", yref = "paper",
  yanchor = "bottom", xanchor = "left",
  align = "left", x = 0, y = 1.2, 
  showarrow = FALSE
)

plots <- list()
idx <- 0
for (hub in hub_cities$closest_metro){
  idx <- idx + 1
  
  a <- list(
    text = hub_cities$closest_metro[idx],
    xref = "paper",
    yref = "paper",
    yanchor = "bottom",
    xanchor = "center",
    align = "center",
    x = 0.5,
    y = 1,
    showarrow = FALSE
  )
  
  data <- afr_cities %>%
    filter(closest_metro == hub) %>%
    filter(dist_to_metro < 500) %>%
    arrange(dist_to_metro)

  #fit <- lm(Builtup ~ dist_to_metro, data = data)
  fit <- lm(Population_2015 ~ dist_to_metro, data = data)
   
  p <- plot_ly(data, x = ~dist_to_metro, y = ~Population_2015, 
               height = 800, width = 500) %>%
    
       add_trace(type = "scatter", mode = "markers", hoverinfo = 'text',
                  text = paste("Name of town: ", data$Agglomeration_Name, "<br>", 
                           "Altitude: ", data$Altitude),
                  marker = list(size = 3, 
                                color = color[1],
                                opacity = .33), 
                  showlegend = FALSE) %>%
     
       add_trace(x = ~dist_to_metro, y = fitted(fit), mode = "lines",
                  name = "",
                  line = list(width = 2,
                              color = color[2])) %>%

      layout(yaxis = list(title = "Population",
                          range = c(3, 8),
                          type = 'log',
                        zeroline = FALSE), 
           
             xaxis = list(title = "Distance from Closest Metro",
                      zeroline = FALSE), 
           
           annotations = a)   #%>%
  
  plots <- c(plots, list(p)) 

}
    
subplot(plots, nrows = nrow(hub_cities), shareX = TRUE, shareY = TRUE, titleY = TRUE, titleX = TRUE) %>%
  layout(annotations = title, showlegend = FALSE) %>%
  config(collaborate = FALSE, displaylogo = FALSE, displayModeBar = FALSE)
```

#Categorical Variable
From https://www.governing.com/gov-data/residential-racial-segregation-metro-areas.html 

##Reading and formating the data
```{r}
GET('http://images.centerdigitaled.com/documents/segregation-national-download.csv', 
    write_disk(us_cities_impt <- tempfile(fileext = ".csv")))

us_cities <- read.csv(us_cities_impt)

#Separating city and state
us_cities <- separate(data = us_cities, col = MSA, into = c("City", "State"), sep = ",")
#Cities are on the border of two states and will be removed
us_cities <- us_cities[!grepl("-",us_cities$State),]
#Keeping only columns of interest
us_states <- us_cities[,c("State", "Black.Population", "White.Population..Non.Hispanic.", "Hispanic.Population", "Asian.Population")]

us_states$Black.Population <- as.numeric(gsub(",","", as.character(us_states$Black.Population)))
us_states$White.Population..Non.Hispanic. <- as.numeric(gsub(",","", as.character(us_states$White.Population..Non.Hispanic.)))
us_states$Hispanic.Population <- as.numeric(gsub(",","", as.character(us_states$Hispanic.Population)))
us_states$Asian.Population <- as.numeric(gsub(",","", as.character(us_states$Asian.Population)))

#Grouping race populations by state
us_states <- aggregate(.~ State, us_states, FUN=sum)

#Calculate total sample population of each state
us_states$TotalPop <- apply(us_states[-1],1,sum)

#Convert counts to percentages
us_states$Black.Population <- round(us_states$Black.Population/us_states$TotalPop *100, 1)
us_states$White.Population..Non.Hispanic. <- round(us_states$White.Population..Non.Hispanic./us_states$TotalPop*100, 1)
us_states$Hispanic.Population <- round(us_states$Hispanic.Population/us_states$TotalPop*100, 1)
us_states$Asian.Population <- round(us_states$Asian.Population/us_states$TotalPop*100, 1)

```

##Plotting racial breakdown of states from population samples
```{r}
color <- brewer.pal(4, "Set1")
plot_ly(us_states, x = ~State, y = ~Black.Population, 
        type = 'bar',
        name = 'Black Population',
        marker = list(color = color[1]),
        text = paste("<b>State:</b>", us_states$State, "<br><b>Sample Population:</b>", prettyNum(us_states$TotalPop,big.mark=",",scientific=FALSE)),
        hoverinfo = "text+y") %>%
  add_trace(y = ~White.Population..Non.Hispanic., 
            name = 'White Population',
            marker=list(color = color[2])) %>%
  add_trace(y = ~Hispanic.Population, 
            name = 'Hispanic Population',
            marker=list(color = color[3])) %>%
  add_trace(y = ~Asian.Population, 
            name = 'Asian Population',
            marker=list(color = color[4])) %>%
  layout(margin = list(t = 80),
         barmode = 'stack', 
         annotations = list(text = "Racial Breakdown of Urban Areas in US States", 
                            showarrow = FALSE, 
                            font = list(size = 19), 
                            x = 0.5, 
                            xref = "paper", 
                            xanchor = "center", 
                            y = 1.2, 
                            yref = "paper"),
         yaxis = list(title = "Percent of Population",
                      ticksuffix = "%",
                      zeroline = FALSE))   %>%
  add_annotations(text = paste0("Based on Data from 273 Cities in 43 States"), 
                  showarrow = FALSE, 
                  font = list(size = 16), 
                  x = 0.5, 
                  xref = "paper", 
                  xanchor = "center", 
                  y = 1.12, 
                  yref = "paper")
```

##Looking at a sample of 5 random states
Because there is data from 43 states, we decided to choose five random states to look at. Using this subset, we created a second chart below, which is easier to interpret.
```{r}
set.seed(1)
index <- sample(1:nrow(us_states), 5)
us_sub <- us_states[index,]

plot_ly(us_sub, x = ~State, y = ~Black.Population, 
        type = 'bar',
        name = 'Black Population',
        marker = list(color = color[1]),
        text = paste("<b>State:</b>", us_sub$State, "<br><b>Sample Population:</b>", prettyNum(us_sub$TotalPop,big.mark=",",scientific=FALSE)),
        hoverinfo = "text+y") %>%
  add_trace(y = ~White.Population..Non.Hispanic., 
            name = 'White Population',
            marker=list(color = color[2])) %>%
  add_trace(y = ~Hispanic.Population, 
            name = 'Hispanic Population',
            marker=list(color = color[3])) %>%
  add_trace(y = ~Asian.Population, 
            name = 'Asian Population',
            marker=list(color = color[4])) %>%
  layout(margin = list(t = 80),
         barmode = 'stack', 
         annotations = list(text = "Racial Breakdown of Urban Areas in Five US States", 
                            showarrow = FALSE, 
                            font = list(size = 19), 
                            x = 0.5, 
                            xref = "paper", 
                            xanchor = "center", 
                            y = 1.2, 
                            yref = "paper"),
         yaxis = list(title = "Percent of Population",
                      ticksuffix = "%",
                      zeroline = FALSE))

```

```{r echo=FALSE}
violin_us <- us_states_long %>%
  plot_ly(
    x= ~State,
    y= ~race,
    split = ~race,
    type='violin',
    box=list(visible=TRUE)
  ) %>%
  layout(
    xaxis = list(
      title = "State"
    )
  )
violin_us
states=unique(us_states$State)
bl_pops <- matrix(NA,length(states))
#for (i in 1:length(states)){
  times_val <- us_states_long %>% filter(State==states[i]) %>% filter(race=='Black.Population') %>% select(proportion)
bl_pops[i] <- rep(x=states[i],times=times_val*10)
#bl_pops<-cbind(matrix('BL',length(states)),)
#}
head(bl_pops)
```

```{r}
state_us_cities <- us_cities %>% filter(State %in% States)
head(state_us_cities)
state_us_cities$Black.Population<-as.character(state_us_cities$Black.Population)
state_us_cities$Black.Population<-as.numeric(gsub(',','',state_us_cities$Black.Population))
state_us_cities$White.Population..Non.Hispanic.<-as.character(state_us_cities$White.Population..Non.Hispanic.)
state_us_cities$White.Population..Non.Hispanic.<-as.numeric(gsub(',','',state_us_cities$White.Population..Non.Hispanic.))
state_us_cities$Black.White.Dissimilarity<-as.numeric(state_us_cities$Black.White.Dissimilarity)
head(state_us_cities)
```

```{r}
States <- c(' NY',' TX',' CA',' FL')
BL <- state_us_cities %>% group_by(State) %>%
  summarise(BLpop = sum(Black.Population), WHpop = sum(White.Population..Non.Hispanic.),BWdis = mean(Black.White.Dissimilarity, na.rm = TRUE)*(BLpop+WHpop))
BL

BL_pop <- BL$BLpop
BW_dis <- BL$BWdis
WHpop <- BL$WHpop

data <- data.frame(States,BL_pop,BW_dis)

p <- plot_ly(data,x=~States,y=~BL_pop,type='bar',name='BL Population') %>%
  add_trace(y=~BW_dis,name='Black/White Disparity') %>%
  add_trace(y=~WHpop,name='WH Population') %>%
  layout(yaxis = list(title = 'Population'), barmode='group')
p
```

```{r}
States <- c(' FL',' CA',' TX',' NY')
BL_pop <- us_cities[us_cities$State %in% States,]
BL_pop <- BL_pop[, -2]

BL_states <- aggregate(.~ State, BL_pop, FUN=sum)
BL_states

```





